#!/usr/bin/env bash

set -e

CI= bun x sherif --fix
bun x prettier --write "**/*.{mjs,js,jsx,ts,tsx,json,md,yaml,yml}"

# Check for changes
if ! git diff --quiet HEAD; then
    git add -A
    git commit -m "auto: format code"
    git push origin HEAD
    echo "pushed changes"
else
    echo "no changes"
fi
